CREATE DATABASE IF NOT EXISTS storeDB;
USE storeDB;

DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Items;

CREATE TABLE IF NOT EXISTS Customers (
customerID INT NOT NULL AUTO_INCREMENT,
customerForename VARCHAR(20) NOT NULL,
customerSurname VARCHAR(30) NOT NULL,
PRIMARY KEY (customerID)
);

CREATE TABLE IF NOT EXISTS Items (
itemID INT NOT NULL AUTO_INCREMENT,
itemName VARCHAR(40) NOT NULL,
itemCost DOUBLE NOT NULL,
PRIMARY KEY (itemID)
);

CREATE TABLE IF NOT EXISTS Orders (
orderID INT NOT NULL AUTO_INCREMENT,
orderDate DATE NOT NULL,
fk_customerID INT NOT NULL,
fk_itemID INT NOT NULL,
PRIMARY KEY (orderID),
FOREIGN KEY (fk_customerID) REFERENCES Customers(customerID),
FOREIGN KEY (fk_itemID) REFERENCES Items(itemID)
);


SELECT * FROM Customers;
SELECT * FROM Items;
SELECT * FROM Orders;